lds_rail:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  lds_rail_position_controller:
    type: effort_controllers/JointPositionController
    joint: lds_rail
    pid: {p: 100.0, i: 1.0, d: 1.0}
