sick5xx_revolute:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  sick5xx_revolute_position_controller:
    type: effort_controllers/JointPositionController
    joint: sick5xx_revolute
    pid: {p: 1000.0, i: 1.0, d: 0.0}

